sudo: required
dist: trusty
language: cpp

os:
  - linux
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - clang

branches:
  - master
    
install:
  - if [[ "$CXX" = "g++" ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -P test/build_and_run.cmake; fi
